global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'my_go_app'
    static_configs:
      - targets: ['host.docker.internal:2112'] # Use host.docker.internal to refer to the host machine from Docker